const express = require('express')
const app = express()
const router = require('./routes')
const bodyParser = require('body-parser')
const cors = require('cors')
app.use(bodyParser.urlencoded({extended : false}))
app.use(cors())
app.use(router)
app.listen(8080, () => {
    console.log("Server Listeing on Port 8080")
})